sudo: false
language: elixir
elixir:
  # - 1.3.4
  - 1.6.3
otp_release:
  # - 18.3
  # - 19.1
  - 20.0
before_install:
  - "sudo apt-get install -y zookeeper"
  - "find / -name zkCli.sh"
before_script:
  - "sudo service zookeeper-server init"
  - "sudo service zookeeper-server start"
after_script:
  - "sudo service zookeeper-server stop"
script:
  - echo "===> Running with Erlang $TRAVIS_OTP_RELEASE";
    if [ "$TRAVIS_OTP_RELEASE" == "19.1" ]; then
      echo "===> Testing with code coverage";
      MIX_ENV=test mix coveralls.travis;
    else
      echo "===> Testing without code coverage";
      MIX_ENV=test mix test;
    fi
