sudo: false
language: elixir
elixir:
  # - 1.3.4
  - 1.6.3
otp_release:
  # - 18.3
  # - 19.1
  - 20.0
before_install:
  - "sudo apt-get install -y zookeeper"
before_script:
  - "sudo /usr/share/zookeeper/bin/zkServer.sh start"
after_script:
  - "sudo /usr/share/zookeeper/bin/zkServer.sh stop"
script:
  - MIX_ENV=test mix coveralls.travis;
